### ISSUE TITLE
Let's GUI

### ISSUE THREAD

**Issue by gokatz** [gossi/ember-cli-create#1]
🎆Wowed to see this. Thanks for this @gossi. I think now we can think of a GUI similar to https://cli.vuejs.org/dev-guide/ui-info.html

**Comment by gossi** [comment]
Absolutely! I've already run some experiments for GUI and the way I want it to be done.

Though, I'm working on the next ember-cli-create version as we speak, there needs to go in some functionality before talking about GUI. When I'm done, will write a blog post, also touch what needs to be done from ember side, to support a GUI for cli to create an enjoyable experience.

**Comment by gokatz** [comment]
love to pitch in anytime 🙂

**Comment by gokatz** [comment]
found something related in the forum 
https://discuss.emberjs.com/t/localdev-tool-ember-hearth-next/15284
inspired by Vue GUI
