### ISSUE TITLE
Version 0.0.5 reports version to be 0.0.1

### ISSUE THREAD

**Issue by CodingItWrong** [gossi/ember-cli-create#15]
The `--version` flag doesn't seem to be reporting the updated version number.

```
~/apps/temp # npm install -g ember-cli-create
...
+ ember-cli-create@0.0.5
added 212 packages from 77 contributors in 12.702s
~/apps/temp # ember-cli-create --version
0.0.1
```

**Comment by gossi** [comment]
```
$ ember-cli-create --version
0.0.5
```

works fine for me. Some cache for you? npm/npx stuff. Maybe go with `which ember-cli-create` to check this is the one you are referring to?

**Comment by CodingItWrong** [comment]
Works now; it was probably something related to me changing my default Node version or something.
