### ISSUE TITLE
Addon proposal: ember-auto-import

### ISSUE THREAD

**Issue by CodingItWrong** [gossi/ember-cli-create#4]
I'd like to suggest including ember-auto-import as an option for users to choose:

https://github.com/ef4/ember-auto-import

One of users' biggest pain points with Ember in the 2018 survey was the difficulty importing generic NPM packages, and since then ember-auto-import has made it extremely easy. It feels like the kind of foundational addon that would be in many apps going forward.

**Comment by gossi** [comment]
This is in now, with `0.0.2`
