### ISSUE TITLE
If qunit-dom not chosen, newer version of qunit-dom installed

### ISSUE THREAD

**Issue by CodingItWrong** [gossi/ember-cli-create#7]
If I don't choose the qunit-dom option I would expect it not to be included in the generated project's package.json—especially because if I'm using mocha I need to ensure qunit-dom is not installed.

Currently if I select qunit-dom it's added to package.json with version constraint `^0.7.1`, but if I deselect qunit-dom it's still added to package.json, with a _newer_ version: `^0.8.0`! This is surprising both because it's included in both cases, and also because if I choose qunit-dom I would hope to have the newest version constraint on it.

**Comment by gossi** [comment]
At the moment, it is just adding things on top of what ember installs (only removing jquery). So that might be coming from ember itself ?!?

**Comment by CodingItWrong** [comment]
I'm pretty sure it's added by Ember itself, in 3.4 if not earlier. If that's the case, then maybe it is no longer necessary to have qunit-dom as an option.

I'm researching mocha setup right now to create another issue to report, and in *that* case it will likely be necessary to remove qunit-dom. But I don't think it's necessary to give people the option to opt out of qunit-dom directly.

**Comment by CodingItWrong** [comment]
Closing as there's not momentum on addressing. It's not a big deal of an issue
